{% set version = "2.0.7" %}

package:
  name: bob.ip.optflow.hornschunck
  version: {{ version }}

source:
  fn: bob.ip.optflow.hornschunck-{{ version }}.zip
  md5: d7421b83072fb263d01cf5dde6f69cca
  url: https://pypi.io/packages/source/b/bob.ip.optflow.hornschunck/bob.ip.optflow.hornschunck-{{ version }}.zip

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - python
    - setuptools
    - bob.extension
    - bob.blitz
    - bob.core
    - bob.sp
    - bob.io.base
    - bob.ip.color
    - scipy
    - pkg-config

  run:
    - python
    - bob.extension
    - bob.blitz
    - bob.core
    - bob.sp
    - bob.io.base
    - bob.ip.color
    - scipy

test:
  commands:
    - nosetests -sv bob.ip.optflow.hornschunck

  imports:
    - bob
    - bob.ip
    - bob.ip.optflow
    - bob.ip.optflow.hornschunck
    - bob.ip.optflow.hornschunck.example

  requires:
    - nose

about:
  home: https://github.com/bioidiap/bob.ip.optflow.hornschunck
  license: GNU General Public License v3 (GPLv3)
  summary: Python bindings to the optical flow framework of Horn & Schunck

extra:
  recipe-maintainers:
    - 183amir
